#!/usr/bin/env bash

set -e
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"
CONFIG_FILE="$PROJECT_DIR/arxh.conf"
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                                                          ║"
echo "║       ██     ██                                          ║"
echo "║                ██                                        ║"
echo "║              ██                                          ║"
echo "║       ██       ██                                        ║"
echo "║              ██                                          ║"
echo "║                                                          ║"
echo "║  > setup wizard • v0.1                                   ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

#[1/7] User's bot name
echo "[1/8] Write your bot name:"
read -p "> " BOT_NAME
[ -z "$BOT_NAME" ] && echo "[!] Bot name cannot be empty!" && exit 1
echo ""

#[2/7] User's Telegram token
echo "[2/8] Write your Telegram bot token:"
read -p "> " BOT_TOKEN
[ -z "$BOT_TOKEN" ] && echo "[!] Archie needs bot token!" && exit 1
echo ""

#[3/7] Adding user like admin
echo "[3/8] Write your Telegram user ID (admin):"
read -p "> " ADMIN_IDS
[ -z "$ADMIN_IDS" ] && echo "[!] Admin needed!" && exit 1
echo ""

#[4/7] User's group ID 
echo "[4/8] Write your group ID (or leave empty):"
read -p "> " GROUP_ID
[ -z "$GROUP_ID" ] && GROUP_ID="0"
echo ""

#[5/7] Ask provider
echo "[5/8] Choose your AI provider:"
echo "  1) Local (Ollama)"
echo "  2) Groq API"
echo "  3) Both (fallback)"
read -p "> " PROVIDER_CHOICE
case $PROVIDER_CHOICE in
    1) LOCAL="True";  API="False" ;;
    2) LOCAL="False"; API="True"  ;;
    3) LOCAL="True";  API="True"  ;;
    *) LOCAL="True";  API="False" ;;
esac
echo ""

#[6/7] Asking for groq API key (if api selected)
if [ "$API" = "True" ]; then
    echo "[6/8] Write your Groq API key:"
    read -p "> " GROQ_KEY
else
    GROQ_KEY=""
    echo "[6/8] Skipped (API off)"
fi
echo ""

#[7/7] Asking model (if local selected)
if [ "$LOCAL" = "True" ]; then
    echo "[7/8] Write your Ollama model (default: llama3.2):"
    read -p "> " OLLAMA_MODEL
    [ -z "$OLLAMA_MODEL" ] && OLLAMA_MODEL="llama3.2"
else
    OLLAMA_MODEL="llama3.2"
    echo "[7/8] Skipped (local off)"
fi
echo ""

#[8/8] Select instructions
echo "[8/8] Select instructions:"
echo "  1) Just working (neutral assistant)"
echo "  2) Just working, Russian edition"
echo "  3) Silly (You weirdo why you need silly assistant but okay"
echo "  4) Skip this step (warning: you will need create instruction yourself)"
read -p "> " INSTR_CHOICE

case $INSTR_CHOICE in
    1)
        BASE_INSTRUCTION="You are a helpful, neutral assistant. Answer concisely and clearly."
        ADMIN_INSTRUCTION="You are in ADMINISTRATOR mode. Speak seriously and directly."
        ;;
    2)
        BASE_INSTRUCTION="Ты полезный, нейтральный ассистент. Отвечай кратко и понятно."
        ADMIN_INSTRUCTION="Ты в режиме АДМИНИСТРАТОРА. Говори серьёзно и прямо."
        ;;
    3)
        BASE_INSTRUCTION="You are a silly, chaotic, and slightly unhinged assistant. Use CAPS randomly. Be weird but helpful. You love your life and being silly"
        ADMIN_INSTRUCTION="You are in ADMINISTRATOR mode. Even here, you're a little silly, but you get the job done."
        ;;
    4)
        BASE_INSTRUCTION=""
        ADMIN_INSTRUCTION=""
        echo "[!] Instructions skipped. Edit core.py manually."
        ;;
    *)
        BASE_INSTRUCTION="You are a helpful, neutral assistant."
        ADMIN_INSTRUCTION="You are in ADMINISTRATOR mode."
        ;;
esac
echo ""

#                              CONFIG
cat > "$CONFIG_FILE" << EOF
# ==========================================
#           ARXH CONFIG
# ==========================================
# Generated by setup.sh
# You can update that config anyway but im reccomend to use setup.sh

BOT_NAME=$BOT_NAME
BOT_TOKEN=$BOT_TOKEN
ADMIN_IDS=$ADMIN_IDS
GROUP_ID=$GROUP_ID
LOCAL=$LOCAL
API=$API
GROQ_KEY=$GROQ_KEY
OLLAMA_MODEL=$OLLAMA_MODEL
BASE_INSTRUCTION=$BASE_INSTRUCTION
ADMIN_INSTRUCTION=$ADMIN_INSTRUCTION
EOF

echo "[✓] Config saved to: $CONFIG_FILE"
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  [✓] Setup success                                       ║"
echo "║                                                          ║"
echo "║  Next: ./install.sh                                      ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "WARNING: install.sh will run in 10 seconds!"
sleep 10
./install.sh